---
- name: Run Apache Example
  hosts: all
  become: true
  tasks:
    - name: Ensure Apache is installed
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
 
    - name: Ensure Apache is running
      ansible.builtin.service:
        name: apache2
        state: started